import { Template } from '@/types/domain'

export const DEFAULT_TEMPLATES: Template[] = [
  {
    metadata: {
      id: 'tpl-brunch-menu',
      slug: 'weekend-brunch-menu',
      title: 'Weekend brunch menu',
      description: 'Warm cafe & bistro menu with customizable food categories and specials.',
      category: 'Menus',
      sizeLabel: 'A4',
      badgeLabel: 'Most loved',
      colorTheme: 'terracotta',
      icon: '☕',
      isPremium: false,
      isFeatured: true,
      version: 1,
      createdAt: '2026-01-15T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    design: {
      schemaVersion: 1,
      canvas: {
        width: 840,
        height: 1188,
        unit: 'px',
        orientation: 'portrait',
        bleedMm: 3,
        safeMarginMm: 5,
      },
      background: {
        color: '#e6aa8f',
      },
      fontsUsed: ['Georgia', 'Inter', 'Helvetica'],
      elements: [
        {
          id: 'bg-art-card',
          type: 'shape',
          name: 'Menu Card Container',
          shapeType: 'rectangle',
          x: 40,
          y: 40,
          width: 760,
          height: 1108,
          fill: '#fffdf9',
          stroke: '#e0d8cf',
          strokeWidth: 2,
          opacity: 0.98,
          zIndex: 1,
          permissions: {
            editable: false,
            movable: false,
            resizable: false,
            rotatable: false,
            deletable: false,
            locked: true,
            required: true,
            visible: true,
          },
        },
        {
          id: 'brand-headline',
          type: 'text',
          name: 'Restaurant / Cafe Name',
          text: 'The Morning Table',
          fontFamily: 'Georgia',
          fontSize: 54,
          fontWeight: 700,
          fill: '#242322',
          textAlign: 'center',
          x: 80,
          y: 110,
          width: 680,
          height: 70,
          zIndex: 2,
          quickEditKey: 'businessName',
          quickEditLabel: 'Business name',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: false,
            locked: false,
            required: true,
            visible: true,
          },
        },
        {
          id: 'sub-tagline',
          type: 'text',
          name: 'Tagline',
          text: 'Slow mornings, artisanal coffees & good food',
          fontFamily: 'Helvetica',
          fontSize: 20,
          fontWeight: 400,
          fill: '#8b5e52',
          textAlign: 'center',
          x: 80,
          y: 190,
          width: 680,
          height: 35,
          zIndex: 3,
          quickEditKey: 'headline',
          quickEditLabel: 'Tagline',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: true,
            locked: false,
            required: false,
            visible: true,
          },
        },
        {
          id: 'special-offer',
          type: 'text',
          name: 'Special Offer',
          text: 'Weekend Brunch Served All Day 8:00 AM – 3:30 PM',
          fontFamily: 'Helvetica',
          fontSize: 18,
          fontWeight: 600,
          fill: '#b84d3b',
          textAlign: 'center',
          x: 80,
          y: 250,
          width: 680,
          height: 30,
          zIndex: 4,
          quickEditKey: 'offerText',
          quickEditLabel: 'Offer text',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: true,
            locked: false,
            required: false,
            visible: true,
          },
        },
        {
          id: 'menu-items-group',
          type: 'text',
          name: 'Menu Selections',
          text: 'Brioche French Toast with Berry Compote — 380 BDT\nPoached Eggs & Smashed Avocado Sourdough — 450 BDT\nSmoked Salmon Bagel with Herb Cream Cheese — 520 BDT\nOrganic Flat White / Batch Brew Coffee — 190 BDT',
          fontFamily: 'Helvetica',
          fontSize: 21,
          lineHeight: 1.8,
          fontWeight: 400,
          fill: '#33312e',
          textAlign: 'center',
          x: 90,
          y: 350,
          width: 660,
          height: 280,
          zIndex: 5,
          quickEditKey: 'menuItems',
          quickEditLabel: 'Featured items',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: true,
            locked: false,
            required: false,
            visible: true,
          },
        },
        {
          id: 'contact-info',
          type: 'text',
          name: 'Contact & Website',
          text: 'morningtable.co · 24 Willow Lane · Reserve: +880 1711 000000',
          fontFamily: 'Helvetica',
          fontSize: 16,
          fontWeight: 500,
          fill: '#837b74',
          textAlign: 'center',
          x: 80,
          y: 1040,
          width: 680,
          height: 30,
          zIndex: 6,
          quickEditKey: 'website',
          quickEditLabel: 'Website / Address',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: true,
            locked: false,
            required: false,
            visible: true,
          },
        },
      ],
    },
  },
  {
    metadata: {
      id: 'tpl-visiting-card',
      slug: 'freshly-baked-cards',
      title: 'Freshly baked',
      description: 'Clean modern visiting card for artisans, chefs, and creative founders.',
      category: 'Business cards',
      sizeLabel: 'Card',
      badgeLabel: 'Popular',
      colorTheme: 'cream',
      icon: '✳',
      isPremium: false,
      isFeatured: true,
      version: 1,
      createdAt: '2026-02-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    design: {
      schemaVersion: 1,
      canvas: {
        width: 1050,
        height: 600,
        unit: 'px',
        orientation: 'landscape',
        bleedMm: 3,
        safeMarginMm: 4,
      },
      background: {
        color: '#f9f6f0',
      },
      fontsUsed: ['Georgia', 'Helvetica', 'Inter'],
      elements: [
        {
          id: 'card-border',
          type: 'shape',
          name: 'Outer Border Guide',
          shapeType: 'rectangle',
          x: 35,
          y: 35,
          width: 980,
          height: 530,
          fill: '#ffffff',
          stroke: '#e6ded4',
          strokeWidth: 2,
          zIndex: 1,
          permissions: {
            editable: false,
            movable: false,
            resizable: false,
            rotatable: false,
            deletable: false,
            locked: true,
            required: true,
            visible: true,
          },
        },
        {
          id: 'person-name',
          type: 'text',
          name: 'Full Name',
          text: 'Aiman Chowdhury',
          fontFamily: 'Georgia',
          fontSize: 44,
          fontWeight: 700,
          fill: '#242322',
          textAlign: 'left',
          x: 90,
          y: 110,
          width: 500,
          height: 55,
          zIndex: 2,
          quickEditKey: 'name',
          quickEditLabel: 'Full Name',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: false,
            locked: false,
            required: true,
            visible: true,
          },
        },
        {
          id: 'person-title',
          type: 'text',
          name: 'Designation / Role',
          text: 'Lead Pastry Chef & Founder',
          fontFamily: 'Helvetica',
          fontSize: 22,
          fontWeight: 500,
          fill: '#b84d3b',
          textAlign: 'left',
          x: 90,
          y: 175,
          width: 500,
          height: 35,
          zIndex: 3,
          quickEditKey: 'designation',
          quickEditLabel: 'Designation',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: true,
            locked: false,
            required: false,
            visible: true,
          },
        },
        {
          id: 'company-name',
          type: 'text',
          name: 'Company / Bakery Name',
          text: 'Freshly Baked Artisans',
          fontFamily: 'Georgia',
          fontSize: 26,
          fontWeight: 600,
          fill: '#594d45',
          textAlign: 'left',
          x: 90,
          y: 290,
          width: 480,
          height: 40,
          zIndex: 4,
          quickEditKey: 'companyName',
          quickEditLabel: 'Company Name',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: false,
            locked: false,
            required: true,
            visible: true,
          },
        },
        {
          id: 'contact-details',
          type: 'text',
          name: 'Contact Numbers & Email',
          text: 'Phone: +880 1819 123456\nEmail: hello@freshlybaked.com\nStudio: House 14, Road 7, Banani, Dhaka',
          fontFamily: 'Helvetica',
          fontSize: 18,
          lineHeight: 1.6,
          fontWeight: 400,
          fill: '#6c655d',
          textAlign: 'left',
          x: 90,
          y: 355,
          width: 650,
          height: 120,
          zIndex: 5,
          quickEditKey: 'contact',
          quickEditLabel: 'Contact Information',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: true,
            locked: false,
            required: false,
            visible: true,
          },
        },
      ],
    },
  },
  {
    metadata: {
      id: 'tpl-summer-market-poster',
      slug: 'summer-market-poster',
      title: 'Summer market',
      description: 'Bold promotional poster for community festivals, pop-ups, and markets.',
      category: 'Posters',
      sizeLabel: 'A3',
      badgeLabel: 'New',
      colorTheme: 'blue',
      icon: '☼',
      isPremium: true,
      isFeatured: true,
      version: 1,
      createdAt: '2026-02-15T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    design: {
      schemaVersion: 1,
      canvas: {
        width: 1188,
        height: 1680,
        unit: 'px',
        orientation: 'portrait',
        bleedMm: 3,
        safeMarginMm: 6,
      },
      background: {
        color: '#8caab0',
      },
      fontsUsed: ['Georgia', 'Helvetica', 'Inter'],
      elements: [
        {
          id: 'poster-header',
          type: 'text',
          name: 'Event Title',
          text: 'SUMMER CRAFT & MAKER MARKET',
          fontFamily: 'Georgia',
          fontSize: 72,
          fontWeight: 700,
          fill: '#1b2c30',
          textAlign: 'center',
          x: 100,
          y: 160,
          width: 988,
          height: 160,
          zIndex: 1,
          quickEditKey: 'headline',
          quickEditLabel: 'Event Title',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: false,
            locked: false,
            required: true,
            visible: true,
          },
        },
        {
          id: 'event-date',
          type: 'text',
          name: 'Dates & Venue',
          text: 'FRIDAY & SATURDAY · OCTOBER 24–25, 2026\nDHAKA BOTANICAL GARDENS AMPHITHEATRE',
          fontFamily: 'Helvetica',
          fontSize: 28,
          fontWeight: 600,
          fill: '#fffdf9',
          textAlign: 'center',
          x: 100,
          y: 380,
          width: 988,
          height: 80,
          zIndex: 2,
          quickEditKey: 'dateVenue',
          quickEditLabel: 'Date & Venue',
          permissions: {
            editable: true,
            movable: true,
            resizable: true,
            rotatable: false,
            deletable: true,
            locked: false,
            required: true,
            visible: true,
          },
        },
      ],
    },
  },
]

export function getTemplateById(id: string): Template | undefined {
  return DEFAULT_TEMPLATES.find((t) => t.metadata.id === id || t.metadata.slug === id)
}

export function getAllTemplates(): Template[] {
  return DEFAULT_TEMPLATES
}
